name: whatsapps_status_saver
description: This app lets you save the whatsapp status and stickers, manage its media, and creating video status.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  fluttertoast: ^8.1.2
  photo_view: ^0.14.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.10
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #  flutter_native_splash: ^2.2.17 # flutter_native_spash & flutter_icons don't work well together, so have to comment one of them
  #  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/status-download.png
    - assets/app-bg.webp

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_icon.png
  # branding: assets/app_icon.png

  color_dark: "#121212"
  image_dark: assets/app_icon_inverted.png
  # branding_dark: assets/app_icon_inverted.png

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#ffffff"

    image_dark: assets/app_icon_inverted.png
    icon_background_color_dark: "#121212"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#121212"

